# **TENSORFLOW**

An open-source deep learning framework developed by **Google** for building and training neural networks.

**Type:** Full end-to-end deep learning framework

**Developer:** Google Brain (2015)

**Core Features for Deep Learning:**

* Supports Dense, Convolutional (CNN), Recurrent (RNN/LSTM/GRU) layers

* **High-level APIs:** `tf.keras`, `tf.data for pipelines`, `tf.losses`, `tf.optimizers`

* **Distributed training:** tf.distribute.Strategy

* Mixed precision & TPU support for faster training

* Custom training loops using GradientTape

**Pros:**

* Excellent for large-scale models, distributed training

* Strong support for production deployment (TF Lite, TF Serving, TensorFlow.js)

* Large library of pretrained models and layers

**Cons:**

* Verbose for custom operations (before TF 2.x)

* Debugging static graphs is difficult

**Real-Life Deep Learning Usage:**

* CNNs for image recognition (Google Photos)

* NLP models (Google Translate)

**Example Use Case:**
Image classification, object detection, NLP models

In [ ]:
import tensorflow as tf
import numpy as np

# Step 1: Convert data to NumPy arrays
x = np.array([1, 2, 3, 4], dtype=float)
y = np.array([2, 4, 6, 8], dtype=float)

# Step 2: Define model using Input layer (recommended)
model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,)),  # preferred over input_shape in Dense
    tf.keras.layers.Dense(1)
])

# Step 3: Compile the model
model.compile(optimizer='sgd', loss='mean_squared_error')

# Step 4: Train the model
model.fit(x, y, epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step - loss: 82.1489
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 57.0524
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 39.6382
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 27.5545
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 19.1696
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 13.3512
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 9.3136
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 6.5118
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 4.5673
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3.2178


# **KERAS**

Type: High-level API (built on top of TensorFlow)

**Developer: **François Chollet (2015), now part of TensorFlow (tf.keras)

**Computation Graph: **Uses TensorFlow backend

**Core Features for Deep Learning:**

* Simple layer stacking (Sequential) or functional API (Model)

* Supports Dense, CNN, RNN, LSTM, GRU layers

* Loss functions, optimizers, metrics ready-to-use

* Callbacks (ModelCheckpoint, EarlyStopping, TensorBoard)

* Data pipelines through tf.data or ImageDataGenerator

**Pros :**

* Very easy to define and train models

* Great for rapid prototyping and small-to-medium DL models

* Integrates seamlessly with TensorFlow ecosystem

Cons:

* Less control over low-level computations

* Not ideal for research experiments requiring dynamic graphs

*Real-Life Deep Learning Usage:**

* Quick prototyping of CNNs, RNNs

Educational purposes, tutorials, Kaggle competitions

Lightweight DL models for mobile apps

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Convert lists to NumPy arrays
x = np.array([1, 2, 3, 4], dtype=float)
y = np.array([2, 4, 6, 8], dtype=float)

# Define the model
model = Sequential([
    Dense(1, input_shape=(1,))  # This works, or you can use tf.keras.Input(shape=(1,))
])

# Compile the model
model.compile(optimizer='sgd', loss='mse')

# Train the model
model.fit(x, y, epochs=10)


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - loss: 7.6876
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 5.3390
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 3.7094
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - loss: 2.5786
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 1.7939
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 1.2494
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.8716
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.6094
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.4274
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.3011


# **PyTorch**

An open-source deep learning framework developed by Facebook (Meta).

**Key Features:**

* Dynamic computation graph → graphs are created on the fly

* Pythonic & easy to debug → very developer-friendly

* Supports GPU acceleration and production deployment

* Widely used in research


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a simple linear model
model = nn.Linear(1, 1)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data
x = torch.tensor([[1.],[2.],[3.],[4.]])
y = torch.tensor([[2.],[4.],[6.],[8.]])

# Training loop
for epoch in range(10):
    optimizer.zero_grad()
    outputs = model(x)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")


Epoch 1, Loss: 41.895172119140625
Epoch 2, Loss: 29.211673736572266
Epoch 3, Loss: 20.410022735595703
Epoch 4, Loss: 14.301898956298828
Epoch 5, Loss: 10.062767028808594
Epoch 6, Loss: 7.120490550994873
Epoch 7, Loss: 5.078081130981445
Epoch 8, Loss: 3.660076856613159
Epoch 9, Loss: 2.6753361225128174
Epoch 10, Loss: 1.9912352561950684


# **TENSORFLOW V/S KEARS V/S PYTORCH**

In [ ]:
# Install tabulate if you haven't already
# pip install tabulate
from tabulate import tabulate

headers = ["Category", "TensorFlow", "Keras", "PyTorch"]
rows = [
    ["Developed By", "Google Brain (2015)", "François Chollet (2015), now part of TensorFlow", "Facebook AI Research (2016)"],
    ["Key Features", "End-to-end DL framework, supports CPU/GPU/TPU, static/dynamic graph, scalable",
     "High-level API, simple layers, rapid prototyping, runs on TF backend",
     "Dynamic computation graph, Pythonic, GPU support, flexible architectures"],
    ["Pros", "Highly scalable, production-ready, deployment support, large ecosystem",
     "Very easy to use, beginner-friendly, fast experimentation",
     "Flexible, easy debugging, research-friendly, good for experimentation"],
    ["Cons", "Verbose syntax, higher learning curve, harder to debug in TF1.x",
     "Less control over low-level ops, limited for highly custom models",
     "Deployment harder, smaller production ecosystem, TorchScript/ONNX needed"],
    ["Real-Life Usage", "Google Translate, Google Photos, Voice assistants, Self-driving car AI",
     "Prototyping AI models, educational purposes, simple ML apps",
     "Facebook AI research projects, NLP models, computer vision research"],
    ["Best For", "Production, large-scale systems", "Beginners, rapid prototyping", "Research, experimentation, dynamic models"]
]

# Print the table
print(tabulate(rows, headers=headers, tablefmt="fancy_grid"))


╒═════════════════╤═══════════════════════════════════════════════════════════════════════════════╤══════════════════════════════════════════════════════════════════════╤══════════════════════════════════════════════════════════════════════════╕
│ Category        │ TensorFlow                                                                    │ Keras                                                                │ PyTorch                                                                  │
╞═════════════════╪═══════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════╡
│ Developed By    │ Google Brain (2015)                                                           │ François Chollet (2015), now part of TensorFlow                      │ Facebook AI Research (2016)                                              │
├───────────────

# **CREATING TENSORS**

A tensor is a multi-dimensional array with:

*  `a data type (dtype)` → like int32, float32

* `a shape `→ how many dimensions and their sizes

* `actual values`

In simple terms: Tensor = **generalization of scalars, vectors, and matrices**

**Rank	Name	Example**

0	-- Scalar	-- 5, 3.14

1	--Vector -- [1, 2, 3]

2	--Matrix -- [[1, 2], [3, 4]]

3+	Higher-rank	Images, videos, batches of data

In [ ]:
import tensorflow as tf

a = tf.constant(10)
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
b = tf.constant([1, 2, 3, 4, 5])              # 1	--Vector -- [1, 2, 3]          # Student marks in 5 subjects ~ 5 features
print(b)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
c = tf.constant([[1, 2], [3, 4]])              # 2	--Matrix -- [[1, 2], [3, 4]]
print(c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.constant([                               # 3+	Higher-rank	Images, videos, batches of data
    [[1, 2], [3, 4]],                           # (height, width, channels) → (224, 224, 3)
    [[5, 6], [7, 8]]
])

**Image as a Tensor**

**Shape:** `(height, width, channels)`

**Example:** `(224, 224, 3)`

**Dataset Batch**

**Shape:** `(batch_size, features)`

**Example:** `(32, 10)`

 **A tensor in TensorFlow is a multi-dimensional array used to represent data and computations in machine learning models.**

 **In deep learning, tensors are used to represent input data, weights, biases, and outputs of a neural network.**

# **Given Code demonstrates how input data is converted into tensors, passed through a neural network layer, and produces an output tensor using learned weight and bias tensors.**

In [ ]:
import tensorflow as tf                                                   # STEP 1 IMPORT TENSORFLOW

In [ ]:
# one data sample with 2 features                                         # STEP 2 INPUT DATA
x = tf.constant([[20.0, 80.0]])   # shape: (1, 2)

`20.0` and` 80.0 `are numerical features

`[[ ]] means:` 1 data sample, 2 input features

**Tensor details:**

**Type:** Tensor

**Shape:** (1, 2)

1 row (sample)

2 columns (features)

In [ ]:
model = tf.keras.Sequential([                                             # STEP 3 Create a Small Nueral Network
    tf.keras.layers.Dense(1, input_shape=(2,))   # Dense(1) → one neuron                                          # activation='relu',
])                                               #Input tensor shape → (2,)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


`Sequential →` layers are arranged one after another

`Dense(1) → `one neuron

`input_shape=(2,) →` neuron expects 2 input values

**TensorFlow automatically creates:**

`Weight tensor` → shape (2, 1)

`Bias tensor` → shape (1,)

In [ ]:
y = model(x)                                                              # STEP 4 FORWARD PASS
print(y)        #  input tensor → weight tensor → bias tensor → output tensor(y)

tf.Tensor([[-21.204035]], shape=(1, 1), dtype=float32)


1. Input tensor x enters the neuron

2. Each input is multiplied by a weight

3. All values are added

4. Bias is added

In [ ]:
weights, bias = model.layers[0].get_weights()

`model.layers[0]`→ first (and only) layer

`get_weights()` → returns: weight tensor and bias tensor

**Shapes:**

`weights →` (2, 1)

`bias → `(1,)

These tensors are learned parameters.

In [ ]:
print("Weights tensor:", weights)                                         # STEP 5 TENSOR VISUALIZATION
print("Bias tensor:", bias)
print("Output tensor:", y)

Weights tensor: [[ 1.2133414]
 [-1.0232362]]
Bias tensor: [0.]
Output tensor: tf.Tensor([[0.]], shape=(1, 1), dtype=float32)


**Neuron formula:**

`Output = (x1 * w1)  + (x2 * w2) + bias`

**Substitute values:**

=(20×−0.90274805)+(80×−1.2492083)+0

=−18.054961+−99.936664

=−117.991625

**Input tensor   →   Weight tensor   →   Multiply & Add   →   Output tensor**

---[20, 80]    ------       [-0.90, -1.24]   -----     (-117.99)     ----------     [-117.99]


# **Deep Learning Pipeline**
1. Data Collection
2. Data Preprocessing
3. Model Design
4. Training
5. Evaluation
6. Deployment



# **TENSORFLOW WITH KERAS (DL PIPELINE)**
**“Binary Classification of Single/Multi-Sample Inputs Using TensorFlow/Keras Sequential Model”**

* Demonstrates building a simple feedforward neural network.

* Uses Dense layers with ReLU hidden layer and Sigmoid output layer.

* Performs forward pass, loss computation, training (backprop), and evaluation.

* Suitable for binary classification tasks with small input samples.

In [ ]:
import tensorflow as tf
# Step 1: Input Data
X = tf.constant([[20.0, 80.0]])       # 1 sample, 2 features
y = tf.constant([[1.0]])              # Binary label

In [ ]:
# Step 2: Model Design
tf_model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(2,)),   # Hidden layer
    tf.keras.layers.Dense(1, activation='sigmoid')                    # Output layer
])

In [ ]:
# Step 3: Model Compilation
tf_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
# Step 4: Model Training
tf_model.fit(X, y, epochs=3, verbose=1)

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0000e+00 - loss: 27.1769
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0000e+00 - loss: 26.5942
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.0000e+00 - loss: 26.0123


In [ ]:
# Step 5: Model Evaluation
loss, accuracy = tf_model.evaluate(X, y)
print("TensorFlow/Keras Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.0000e+00 - loss: 31.5990
TensorFlow/Keras Accuracy: 0.0


# **PYTORCH (DL PIPELINE)**

**“Binary Classification of Single/Multi-Sample Inputs Using PyTorch Dynamic Neural Network”**


* Demonstrates building a simple neural network class (nn.Module).

* Uses manual forward pass, ReLU hidden layer, Sigmoid output, BCELoss, and Adam optimizer.

* Shows training loop, gradient computation, weight updates, and evaluation explicitly.

* Ideal for understanding dynamic computation graph in PyTorch.

In [ ]:
import torch                        # torch → main PyTorch library, handles tensors.
import torch.nn as nn               # torch.nn → contains modules for neural network layers.
import torch.optim as optim         # torch.optim → contains optimizers like Adam, SGD.

# Step 1: Input Data
# --------------------------
X = torch.tensor([[20.0, 80.0]])  # X → input tensor (1 sample, 2 features: 20 & 80).
y = torch.tensor([[1.0]])         # y → target/output tensor (1 sample, binary label 1).

In [ ]:
# Step 2: Model Design
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 16)    # Hidden layer: 2 inputs → 16 neurons
        self.fc2 = nn.Linear(16, 1)    # Output layer: 16 → 1 neuron

    def forward(self, x):
        x = torch.relu(self.fc1(x))     # Apply ReLU activation to hidden layer
        x = torch.sigmoid(self.fc2(x))  # Apply Sigmoid activation to output layer
        return x

model = SimpleNN()

In [ ]:
# Step 3: Loss and Optimizer
criterion = nn.BCELoss()                            # nn.BCELoss() → Binary Cross-Entropy loss, suitable for binary classification.
optimizer = optim.Adam(model.parameters(), lr=0.01) # Adam optimizer; updates model weights automatically.

In [ ]:
# Step 4: Training Loop
epochs = 3
for epoch in range(epochs):
    optimizer.zero_grad()          # Reset gradients before backprop
    y_pred = model(X)              # Forward pass: compute predicted output
    loss = criterion(y_pred, y)    # Compute loss between predicted and target
    loss.backward()                # Backpropagation: compute gradients
    optimizer.step()               # Update weights using gradients
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 1, Loss: 0.0135
Epoch 2, Loss: 0.0001
Epoch 3, Loss: 0.0000


`epochs `= 3 → Number of times we train over the same input.

`for epoch in range(epochs) →` Loop over each epoch.

`optimizer.zero_grad() →` PyTorch accumulates gradients, so we reset them each iteration.

`y_pred = model(X) → `Forward pass through the network; calls forward() internally.

`loss = criterion(y_pred, y) →` Compute how far predictions are from true labels.

`loss.backward() →` Backpropagation: calculates gradients of loss w.r.t each parameter.

`optimizer.step() →` Adjusts the weights using the gradients.

`print(...) →` Shows the loss after each epoch.

In [ ]:
# Step 5: Evaluation
with torch.no_grad():
    y_pred = model(X)
    prediction = (y_pred > 0.5).float()
    accuracy = (prediction == y).sum().item()
    print("PyTorch Prediction:", prediction.item())
    print("PyTorch Accuracy:", accuracy)


PyTorch Prediction: 1.0
PyTorch Accuracy: 1


`with torch.no_grad(): → `Disables gradient tracking (we don’t need gradients during evaluation).

`y_pred = model(X) →` Compute predictions for input.

`prediction = (y_pred > 0.5).float() → `Threshold sigmoid output: >0.5 → 1, else 0.

`accuracy = (prediction == y).sum().item() → `Count how many predictions match target.

`prediction.item() →` Returns the predicted value as a Python scalar.

Prints predicted value and accuracy.

# **TENSORFLOW WITHOUT KERAS**

In [ ]:
import tensorflow as tf

# --------------------------
# Step 1: Input Data
# --------------------------
X = tf.constant([[20.0, 80.0]])
y = tf.constant([[1.0]])

# --------------------------
# Step 2: Initialize weights and bias
# --------------------------
w1 = tf.Variable(tf.random.uniform((2,16), -0.5, 0.5))
b1 = tf.Variable(tf.zeros((16,)))
w2 = tf.Variable(tf.random.uniform((16,1), -0.5, 0.5))
b2 = tf.Variable(tf.zeros((1,)))

# Learning rate
lr = 0.01
epochs = 3

# --------------------------
# Step 3: Training Loop
# --------------------------
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        # Forward pass
        hidden = tf.nn.relu(tf.matmul(X, w1) + b1)
        output = tf.sigmoid(tf.matmul(hidden, w2) + b2)
        # Binary cross-entropy loss
        loss = -y*tf.math.log(output) - (1-y)*tf.math.log(1-output)
        loss = tf.reduce_mean(loss)

    # Compute gradients
    grads = tape.gradient(loss, [w1, b1, w2, b2])

    # Update weights
    w1.assign_sub(lr * grads[0])
    b1.assign_sub(lr * grads[1])
    w2.assign_sub(lr * grads[2])
    b2.assign_sub(lr * grads[3])

    print(f"Epoch {epoch+1}, Loss: {loss.numpy():.4f}")

# --------------------------
# Step 4: Evaluation
# --------------------------
hidden = tf.nn.relu(tf.matmul(X, w1) + b1)
output = tf.sigmoid(tf.matmul(hidden, w2) + b2)
prediction = tf.cast(output > 0.5, tf.float32)
print("TensorFlow Low-Level Prediction:", prediction.numpy())


Epoch 1, Loss: nan
Epoch 2, Loss: nan
Epoch 3, Loss: nan
TensorFlow Low-Level Prediction: [[0.]]
